---
# this is used for local development and testing
version: "3.0"
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: business-card
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - META_TITLE=Damien Paul Dong
      - META_DESCRIPTION=Damien Paul Dong
      - META_AUTHOR=Damien Paul Dong
      - META_KEYWORDS=Artist, Technologist, Experience Designer, Experiential Marketing, Consultant, Interactive Designer, Multimedia Engineer, Project Manager
      - LANG=en
      - META_INDEX_STATUS=noindex
      - THEME=Dark
      - GA_TRACKING_ID=G-4N9GDZ721D
      - FAVICON_URL=assets/favicon.png
      - AVATAR_URL=assets/dpd_logo_white_200.png
      - AVATAR_2X_URL=assets/dpd_logo_white_400.png
      - AVATAR_ALT=Damien Paul Dong monogram logo
      - NAME=Damien Paul Dong
      - BIO=Artist, Technologist, Experience Designer
      - FOOTER=Keep in touch!
      # GITHUB=https://github.com/timothystewart6
      # TWITTER=https://twitter.com/TechnoTimLive
      - INSTAGRAM=https://www.instagram.com/djdamienpaul
      # YOUTUBE=https://www.youtube.com/channel/UCOk-gHyjcWZNj3Br4oxwh0A
      # TWITCH=https://www.twitch.tv/rabbitrevolution
      - DISCORD=https://discord.com/users/188376512225869824
      # TIKTOK=https://www.tiktok.com/@technotim
      # KIT=https://kit.co/TechnoTim
      - FACEBOOK=https://facebook.com/damienpauldong
      # FACEBOOK_MESSENGER=https://facebook.com/damienpauldong
      - LINKED_IN=https://www.linkedin.com/in/damienpauldong/
      # PRODUCT_HUNT=https://www.producthunt.com/
      # SNAPCHAT=https://www.snapchat.com/
      # SPOTIFY=https://www.spotify.com/
      # REDDIT=https://www.reddit.com/
      # MEDIUM=https://medium.com
      # PINTEREST=https://www.pinterest.com/
      - EMAIL=damienpauldong@gmail.com
      - EMAIL_TEXT=Email
      # EMAIL_ALT=damienpauldong@gmail.com
      # EMAIL_ALT_TEXT=Email
      - SOUND_CLOUD=https://soundcloud.com/djdamienpaul
      # FIGMA=https://figma.com
      # TELEGRAM=https://t.me/djdamienpaul
      # TUMBLR=https://www.tumblr.com/
      # STEAM=https://steamcommunity.com/
      # VIMEO=https://vimeo.com/damienpauldong
      # WORDPRESS=https://wordpress.com/
      # GOODREADS=https://www.goodreads.com/
      # SKOOB=https://www.skoob.com.br/
      # LETTERBOXD=https://letterboxd.com/
      # MICRO_BLOG=https://micro.blog/
      # WHATSAPP=https://www.whatsapp.com/
      # STRAVA=https://www.strava.com/
      # BUYMEACOFFEE=https://www.buymeacoffee.com/
      # GITLAB=https://www.gitlab.com/
      # PATREON=https://www.patreon.com/technotim
      # DEVTO=https://dev.to/
      # UMAMI_WEBSITE_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      # UMAMI_APP_URL=https://your-umami-app.com
      - BUTTON_ORDER=PORTFOLIO,MOBILE,EMAIL,VCARD,LINKED_IN,INSTAGRAM,DISCORD,SOUND_CLOUD,FACEBOOK,ABOUT
      # PAYPAL=https://www.paypal.me/user
      # SLACK=https://slack.com/
      # STACKOVERFLOW=https://stackoverflow.com/
      # LASTFM=https://last.fm/
      # GITEA=https://gitea.io/
      # POLYWORK=https://www.polywork.com/
      # SIGNAL=https://signal.org/
      # UNTAPPD=https://untappd.com/
      # BUTTON_TARGET=_blank
      # INSTANTGAMING=https://www.instant-gaming.com/
      # GHOST=https://ghost.org/
      # TRAKT=https://trakt.tv
      # CASHAPP=https://cash.app/
      # TEESPRING=https://teespring.com/
      # XING=https://www.xing.com/en
      # KEYBASE=https://keybase.io/
      # ONLYFANS=https://onlyfans.com/
      # SESSION=https://getsession.org/
      # THREEMA=https://threema.ch/en/
      # STREAMLABS=https://streamlabs.com/
      # PRIVATEBIN=https://privatebin.net/
      # AMAZON_AFFILIATE=https://affiliate-program.amazon.co.uk/
      # AMAZON_WISHLIST=https://www.amazon.co.uk/b?node=22758010031
      # APPLE_MUSIC=https://www.apple.com/uk/apple-music/
      # YOUTUBE_MUSIC=https://music.youtube.com/playlist?list=
      # VENMO=https://account.venmo.com/u/DamienPaul
      # STATUS=https://status.im/
      # MATRIX=https://matrix.to/
      # ANILIST=https://anilist.co/
      # GITBUCKET=https://gitbucket.github.io/
      # SHAZAM=https://www.shazam.com/myshazam
      # TPDB=https://theposterdb.com/
      # FLICKR=https://www.flickr.com/
      # OSU=https://osu.ppy.sh/users/
      # LINE=https://line.me/en/
      # KAKAOTALK=https://www.kakaocorp.com/page/service/service/KakaoTalk?lang=ko
      # DESIGNBYHUMANS=https://www.designbyhumans.com/
      # DOCKERHUB=https://hub.docker.com/
      # VERO=https://vero.co/
      # MYANIMELIST=https://myanimelist.net/
      # OG_SITE_NAME=Techno Tim Live (OG)
      # OG_TITLE=Techno Tim (OG)
      # OG_DESCRIPTION=Techno Tim Link page (OG)
      # OG_URL=https://technotim.live/
      # OG_IMAGE=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      # OG_IMAGE_WIDTH=400
      # OG_IMAGE_HEIGHT=400
      # TWITTER_CARD=summary_large_image
      # TWITTER_IMAGE=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      # TWITTER_SITE=@TechnoTimLive
      # TWITTER_CREATOR=@TechnoTimLive
      # SHARE=https://technotim.live
      # FIVEHUNDREDPX=https://500px.com/
      - CUSTOM_BUTTON_TEXT=Portfolio,Mobile,vCard,About This Card
      - CUSTOM_BUTTON_URL=https://damienpauldong.com,tel://+16173200092,assets/dpd_vcard.vcf,https://damienpauldong.com/business-card
      - CUSTOM_BUTTON_COLOR=#444444,#664466,#669944,#886666
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff,#ffffff,#ffffff
      - CUSTOM_BUTTON_ALT_TEXT=Portfolio,Mobile,vCard,About
      - CUSTOM_BUTTON_NAME=PORTFOLIO,MOBILE,VCARD,ABOUT
      - CUSTOM_BUTTON_ICON=fas fa-home,fas fa-phone,fas fa-id-card,fas fa-info-circle
      - VIRTUAL_HOST=hello.damienpauldong.com
      - LETSENCRYPT_HOST=hello.damienpauldong.com

    ports:
      - 8089:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxynet

networks:
  proxynet:
    external: true
